function PopoutMenu(args){var self=this;this.menuIsOpen=false;Object.keys(args).forEach(function(i){self[i]=args[i];})
if(!this.id)this.id='ArcMenu';if(!this.size)this.size=80;if(!this.openTime)this.openTime=100;if(!this.itemSize)this.itemSize=15;if(!this.color)this.color='pink';if(!this.startOClock)this.startOClock=12;if(!this.endOClock)this.endOClock=12;if(!this.radioMenu)this.radioMenu=true;if(!this.popoutMenu)this.popoutMenu=true;this.selectedItem=undefined;while(this.startOClock>=12)this.startOClock-=12;while(this.endOClock>12)this.endOClock-=12;this.arcLength=(this.endOClock-this.startOClock)*Math.PI / 6.0;this.startAngle=this.startOClock*Math.PI / 15.0;this.startAngle-=Math.PI / 2;this.items=[];function Item(args){var self=this;Object.keys(args).forEach(function(i){self[i]=args[i];})}
this.SVG=function(tag){doc=document.implementation.createDocument(null,null,null);return $(doc.createElementNS('http://www.w3.org/2000/svg',tag));}
this.XLINK=function(tag,val){att=document.createAttributeNS('http://www.w3.org/1999/xlink','xlink:'+tag);att.nodeValue=val;return att;}
this.initialize=function(){$("#"+this.id).append("<svg width='"+this.size*2+"' height='"+this.size*2+"' xmlns:xlink='http://www.w3.org/1999/xlink'><g id='g_"+this.id+"'>").data('jqo',this);svgg=$("#g_"+this.id);angle=this.startAngle;for(item of this.items){item.cx=(this.size-item.size)*Math.cos(angle)+this.size;item.cy=(this.size-item.size)*Math.sin(angle)+this.size;angle+=this.arcLength /(this.items.length-1);newg=this.SVG('g').attr('name',this.id).attr('transform','translate('+(this.size-this.itemSize/2)+' '+(this.size-this.itemSize/2)+')').data(item).appendTo(svgg).click(item,function(evt){self.changeSelection(evt.data);return false;});if(this.popoutMenu){newg.attr('display','none');animation=this.SVG("animateTransform").attr('type','translate').attr('from',''+(this.size-this.itemSize/2)+' '+(this.size-this.itemSize/2)).attr('to',''+item.cx+' '+item.cy).attr('begin','indefinite').attr('fill','freeze').attr('dur',this.openTime+'ms');animation.data('direction','open');animation[0].setAttribute('attributeName','transform');animation.appendTo(newg);animation=this.SVG("animateTransform").attr('type','translate').attr('to',''+(this.size-this.itemSize/2)+' '+(this.size-this.itemSize/2)).attr('from',''+item.cx+' '+item.cy).attr('begin','indefinite').attr('fill','freeze').attr('dur',this.openTime+'ms').attr('onend',"hideIcons('"+this.id+"')");animation.data('direction','close');animation[0].setAttribute('attributeName','transform');animation.appendTo(newg);}
circle=this.SVG('circle').attr('cx',0).attr('cy',0).attr('r',item.size).attr('fill',item.color).appendTo(newg);if('icon'in item){use=this.SVG("use").attr('width',item.size).attr('height',item.size).attr('x',-item.size/2).attr('y',-item.size/2).appendTo(newg);att=this.XLINK('href',item.icon);use[0].setAttributeNodeNS(att);}}
this.menuCentre=this.SVG('g').attr('transform','translate('+this.size+' '+this.size+')').appendTo(svgg);if(this.popoutMenu){this.menuCentre.click(this,function(evt){menu=evt.data;menu.toggleMenuOpenCloseState();});}
circle=this.SVG('circle').attr('cx',0).attr('cy',0).attr('r',this.itemSize).attr('fill',this.color).appendTo(this.menuCentre);if('icon'in this){use=this.SVG("use").attr('width',this.itemSize).attr('height',this.itemSize).attr('x',-this.itemSize/2).attr('y',-this.itemSize/2).appendTo(this.menuCentre);att=this.XLINK('href',this.icon);use[0].setAttributeNodeNS(att);}};this.toggleMenuOpenCloseState=function(){if(this.menuIsOpen){this.closeMenu();this.menuIsOpen=false;}else{this.openMenu();this.menuIsOpen=true;}};this.closeMenu=function(){animations=$("[name='"+this.id+"'] > [begin='indefinite']").filter(function(){return $(this).data('direction')=='close';});animations.each(function(animation){this.beginElement();});};this.hideIcons=function(){$("[name='"+this.id+"']").attr("display","none");};this.openMenu=function(){$("[name='"+this.id+"']").removeAttr("display");animations=$("[name='"+this.id+"'] > [begin='indefinite']").filter(function(){return $(this).data('direction')=='open';});animations.each(function(animation){this.beginElement();});};this.addItem=function(args){if(!args.size)args.size=this.itemSize;if(!args.id)args.id="m"+this.items.length+"_"+this.id;if(!args.color)args.color=this.color;this.items.push(new Item(args));};this.setSelectedItem=function(item){this.selectedItem=item;if(this.radioMenu){circle=this.menuCentre.children('circle');circle.attr('fill',item?item.color:this.color);use=this.menuCentre.children('use');att=this.XLINK('href',item?item.icon:this.icon);use[0].setAttributeNodeNS(att);}};this.changeSelection=function(item){if(this.selectedItem!==item){if('callback'in item){item.callback(item,this.selectedItem);}
if('callback'in this){this.callback(item,this.selectedItem);}
this.setSelectedItem(item);}else{this.setSelectedItem(null);}
if(this.popoutMenu){self.toggleMenuOpenCloseState();}};};function hideIcons(id){$("[name='"+id+"']").attr("display","none");}